# Utilizamos una imagen base de MariaDB
FROM mariadb:latest

# Definimos la variable de entorno para establecer la contraseña de root
ENV MARIADB_ROOT_PASSWORD=laboratorio3
ENV MARIADB_DATABASE=lab3
ENV MARIADB_USER=daniel
ENV MARIADB_PASSWORD=laboratorio3

EXPOSE 3306

# CMD ["mysqld"]